apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-img7
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-img7
  template:
    metadata:
      labels:
        app: my-img7
    spec:
      containers:
        - name: minikube
          image: my-img7:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000